import Head from 'next/head'

import Mint from '@/templates/Mint'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Gens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mint />
    </>
  )
}
